name: Deploy Lambda Function
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     cd lambda_function
      #     pip install -r requirements.txt -t .          

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp src/handler.py package/
          cd package
          pip install -r ../src/requirements.txt -t .
          zip -r ../s3_to_newrelic_connector_lambda.zip .
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
  
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve    